# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-23 07:39
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Car_Chasis_Number', models.CharField(blank=True, max_length=19, validators=[django.core.validators.RegexValidator(message="chasis number must be entered in the format: 'MALA351ALDM165832B'. Up to 19 digits allowed.", regex='^MA[A-HJ-NPR-Z0-9]{15}$')])),
                ('Model', models.CharField(max_length=255)),
                ('Type', models.CharField(max_length=255)),
                ('Fuel_Type', models.IntegerField(choices=[(1, 'Petrol'), (2, 'Diesel'), (3, 'CNG/LPG Company Fitted'), (4, 'CNG/LPG Externally Fitted'), (5, 'Electric')], default=None)),
                ('Transmission', models.IntegerField(choices=[(1, 'Automatic'), (2, 'Manual')], default=None)),
                ('Year_of_Manufacture', models.IntegerField(blank=True, choices=[(1950, 1950), (1951, 1951), (1952, 1952), (1953, 1953), (1954, 1954), (1955, 1955), (1956, 1956), (1957, 1957), (1958, 1958), (1959, 1959), (1960, 1960), (1961, 1961), (1962, 1962), (1963, 1963), (1964, 1964), (1965, 1965), (1966, 1966), (1967, 1967), (1968, 1968), (1969, 1969), (1970, 1970), (1971, 1971), (1972, 1972), (1973, 1973), (1974, 1974), (1975, 1975), (1976, 1976), (1977, 1977), (1978, 1978), (1979, 1979), (1980, 1980), (1981, 1981), (1982, 1982), (1983, 1983), (1984, 1984), (1985, 1985), (1986, 1986), (1987, 1987), (1988, 1988), (1989, 1989), (1990, 1990), (1991, 1991), (1992, 1992), (1993, 1993), (1994, 1994), (1995, 1995), (1996, 1996), (1997, 1997), (1998, 1998), (1999, 1999), (2000, 2000), (2001, 2001), (2002, 2002), (2003, 2003), (2004, 2004), (2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016)])),
                ('Number_of_Service', models.PositiveIntegerField(default=0)),
                ('Number_of_KMs_Travelled', models.PositiveIntegerField(default=0)),
                ('Registration_Number', models.CharField(max_length=255)),
                ('Engine_Number', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Garage',
            fields=[
                ('Garage_Name', models.CharField(max_length=500)),
                ('Garage_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('Garage_Location', models.CharField(blank=True, max_length=255)),
                ('Number_of_Two_Post_Lift', models.IntegerField(blank=True)),
                ('Garage_Area', models.IntegerField(blank=True)),
                ('Number_of_Mechanic', models.IntegerField(blank=True)),
                ('Field_of_Expertise', models.IntegerField(choices=[(1, 'Washing'), (2, 'Hard_wash'), (3, 'Cold_wash')], default=None)),
                ('Number_of_Advisor', models.IntegerField()),
                ('Phone_Number_Primary', models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('Phone_Number_Secondary', models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('Product_ID', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('Product_Name', models.CharField(max_length=500)),
                ('Manufacture_Name', models.CharField(blank=True, max_length=500)),
                ('Supplier_Name', models.CharField(max_length=500)),
                ('Date_of_purchase', models.DateField(blank=True)),
                ('Status', models.IntegerField(choices=[(1, 'available'), (2, 'Out of stock')], default=None)),
                ('Price', models.FloatField()),
                ('Discount', models.FloatField()),
                ('Final_Price', models.FloatField()),
                ('SKU_Number', models.CharField(max_length=255)),
                ('Meta_Description', models.TextField(max_length=10000)),
                ('Meta_Keyword', models.CharField(max_length=255)),
                ('Category', models.IntegerField(choices=[(1, 'Engine'), (2, 'Electrical'), (3, 'Brakes'), (4, 'Suspension'), (5, 'Transmission'), (6, 'Body'), (7, 'Heating_Ventilation_Ac')], default=None)),
                ('Sub_Category', models.IntegerField(choices=[(1, 'Engine'), (2, 'Electrical'), (3, 'Brakes'), (4, 'Suspension'), (5, 'Transmission'), (6, 'Body'), (7, 'Heating_Ventilation_Ac')], default=None)),
                ('Image', models.URLField()),
                ('Compatible_Car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compatible_car', to='jsonapi.Car')),
                ('Original_Car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='original_car', to='jsonapi.Car')),
            ],
        ),
    ]
