# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-22 19:42
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Car_Chasis_Number', models.CharField(blank=True, max_length=19, validators=[django.core.validators.RegexValidator(message="chasis number must be entered in the format: 'MALA351ALDM165832B'. Up to 19 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('Car_Manufacture', models.IntegerField(choices=[(1, 'Washing'), (2, 'Hard_wash'), (3, 'Cold_wash')], default=None)),
                ('Model', models.CharField(max_length=255)),
                ('Type', models.CharField(max_length=255)),
                ('Transmission', models.CharField(choices=[(1, 'Petrol'), (2, 'Diesel'), (3, 'Gas'), (4, 'Petrol_Gas'), (5, 'Electric')], default=None, max_length=2)),
                ('Year_of_Manufacture', models.DateTimeField(blank=True)),
                ('Number_of_Service', models.IntegerField()),
                ('Number_of_KMs', models.CharField(blank=True, max_length=1000000000)),
                ('Registration_Number', models.CharField(max_length=255)),
                ('Engine_Number', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Garage',
            fields=[
                ('Garage_Name', models.CharField(max_length=500)),
                ('Garage_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('Garage_Location', models.CharField(blank=True, max_length=255)),
                ('Number_Post_Lift', models.IntegerField(blank=True)),
                ('Garage_Area', models.IntegerField(blank=True)),
                ('Number_Mechanic', models.IntegerField(blank=True)),
                ('Field_of_Expertise', models.CharField(choices=[(1, 'Washing'), (2, 'Hard_wash'), (3, 'Cold_wash')], default=None, max_length=20)),
                ('Number_of_Advisor', models.IntegerField()),
                ('phone_number', models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('Product_ID', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('Product_Name', models.CharField(max_length=500)),
                ('Manufacture_Name', models.CharField(blank=True, max_length=500)),
                ('Supplier_Name', models.CharField(max_length=500)),
                ('Date_of_purchase', models.DateField(blank=True)),
                ('Status', models.CharField(choices=[(1, 'Active'), (2, 'Inactive')], default=None, max_length=10)),
                ('Price', models.FloatField()),
                ('Discount', models.FloatField()),
                ('Final_Price', models.FloatField()),
                ('SKU_Number', models.CharField(max_length=255)),
                ('Meta_Description', models.TextField(max_length=10000)),
                ('Meta_Keyword', models.CharField(max_length=255)),
                ('Category', models.CharField(choices=[(1, 'Engine'), (2, 'Electrical'), (3, 'Brakes'), (4, 'Suspension'), (5, 'Transmission'), (6, 'Body'), (7, 'Heating_Ventilation_Ac')], default=None, max_length=20)),
                ('Sub_Category', models.CharField(choices=[(1, 'Engine'), (2, 'Electrical'), (3, 'Brakes'), (4, 'Suspension'), (5, 'Transmission'), (6, 'Body'), (7, 'Heating_Ventilation_Ac')], default=None, max_length=2)),
                ('Image', models.URLField()),
                ('Compatible_Car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compatible_car', to='jsonapi.Car')),
                ('Original_Car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='original_car', to='jsonapi.Car')),
            ],
        ),
    ]
