# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-22 21:13
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jsonapi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='Number_of_KMs',
        ),
        migrations.AddField(
            model_name='car',
            name='Number_of_KMs_Travelled',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='car',
            name='Car_Chasis_Number',
            field=models.CharField(blank=True, max_length=19, validators=[django.core.validators.RegexValidator(message="chasis number must be entered in the format: 'MALA351ALDM165832B'. Up to 19 digits allowed.", regex='^MA[A-HJ-NPR-Z0-9]{15}$')]),
        ),
        migrations.AlterField(
            model_name='car',
            name='Car_Manufacture',
            field=models.IntegerField(choices=[(1, 'Maruti'), (2, 'Hyundai'), (3, 'Tata Motors'), (4, 'Mahindra and Mahindra'), (5, 'Toyota'), (6, 'Honda'), (7, 'Chevrolet'), (8, 'Volkswagen'), (9, 'Skoda'), (10, 'Fiat'), (11, 'Renault')], default=None),
        ),
        migrations.AlterField(
            model_name='car',
            name='Number_of_Service',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='car',
            name='Transmission',
            field=models.IntegerField(choices=[(1, 'Petrol'), (2, 'Diesel'), (3, 'Gas'), (4, 'Petrol_Gas'), (5, 'Electric')], default=None),
        ),
        migrations.AlterField(
            model_name='car',
            name='Year_of_Manufacture',
            field=models.IntegerField(blank=True, choices=[(1950, 1950), (1951, 1951), (1952, 1952), (1953, 1953), (1954, 1954), (1955, 1955), (1956, 1956), (1957, 1957), (1958, 1958), (1959, 1959), (1960, 1960), (1961, 1961), (1962, 1962), (1963, 1963), (1964, 1964), (1965, 1965), (1966, 1966), (1967, 1967), (1968, 1968), (1969, 1969), (1970, 1970), (1971, 1971), (1972, 1972), (1973, 1973), (1974, 1974), (1975, 1975), (1976, 1976), (1977, 1977), (1978, 1978), (1979, 1979), (1980, 1980), (1981, 1981), (1982, 1982), (1983, 1983), (1984, 1984), (1985, 1985), (1986, 1986), (1987, 1987), (1988, 1988), (1989, 1989), (1990, 1990), (1991, 1991), (1992, 1992), (1993, 1993), (1994, 1994), (1995, 1995), (1996, 1996), (1997, 1997), (1998, 1998), (1999, 1999), (2000, 2000), (2001, 2001), (2002, 2002), (2003, 2003), (2004, 2004), (2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016)]),
        ),
        migrations.AlterField(
            model_name='garage',
            name='Field_of_Expertise',
            field=models.IntegerField(choices=[(1, 'Washing'), (2, 'Hard_wash'), (3, 'Cold_wash')], default=None),
        ),
        migrations.AlterField(
            model_name='product',
            name='Category',
            field=models.IntegerField(choices=[(1, 'Engine'), (2, 'Electrical'), (3, 'Brakes'), (4, 'Suspension'), (5, 'Transmission'), (6, 'Body'), (7, 'Heating_Ventilation_Ac')], default=None),
        ),
        migrations.AlterField(
            model_name='product',
            name='Status',
            field=models.IntegerField(choices=[(1, 'available'), (2, 'Out of stock')], default=None),
        ),
        migrations.AlterField(
            model_name='product',
            name='Sub_Category',
            field=models.IntegerField(choices=[(1, 'Engine'), (2, 'Electrical'), (3, 'Brakes'), (4, 'Suspension'), (5, 'Transmission'), (6, 'Body'), (7, 'Heating_Ventilation_Ac')], default=None),
        ),
    ]
