# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-27 13:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jsonapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='garage',
            name='Address',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='jsonapi.Address'),
        ),
    ]
