# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-22 21:21
from __future__ import unicode_literals

from django.db import migrations
import jsonapi.models


class Migration(migrations.Migration):

    dependencies = [
        ('jsonapi', '0002_auto_20160722_2113'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Tags',
            field=jsonapi.models.CommaSepField(default='Ashish'),
        ),
    ]
