# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-23 05:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jsonapi', '0003_product_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='Transmission',
            field=models.IntegerField(choices=[(1, 'Petrol'), (2, 'Diesel'), (3, 'CNG/LPG Company Fitted'), (4, 'CNG/LPG Externally Fitted'), (5, 'Electric')], default=None),
        ),
    ]
