# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-23 05:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jsonapi', '0004_auto_20160723_0533'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='Tags',
        ),
    ]
