# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-23 05:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.IntegerField(choices=[(1, 'ENGINE'), (2, 'BRAKES'), (3, 'TRANSMISSION'), (4, 'SUSPENSION'), (5, 'BODY'), (6, 'ELECTRICAL'), (7, 'HEATING VENTILATION & A')]),
        ),
        migrations.AlterField(
            model_name='product',
            name='imageUrl',
            field=models.URLField(default='default.jpg'),
        ),
        migrations.AlterField(
            model_name='product',
            name='subcategory',
            field=models.IntegerField(choices=[(1, 'FILTERS')]),
        ),
    ]
